#!/bin/sh
# Extremely simple script for copying certain files

cp ~/.tmux.conf ./tmux
echo ".tmux.conf copied successfully in /Tmux"
echo ""

cp ~/.tmux/left_status.sh ./tmux
echo ".tmux/left_status copied successfully in /Tmux"
echo ""

cp ~/.tmux/right_status.sh ./tmux
echo ".tmux/right_status copied successfully in /Tmux"
echo ""

cp ~/.vimrc ./vim
echo ".vimrc copied successfully in /vim"
echo ""

cp ~/.gvimrc ./vim
echo ".gvimrc copied successfully in /vim"
echo ""

cp ~/.config/awesome/rc.lua ./awesomeWM
echo "rc.lua copied successfully in /awesomeWM"
echo ""

cp ~/.config/awesome/theme.lua ./awesomeWM
echo "theme.lua copied successfully in /awesomeWM"
echo ""

cp ~/.bashrc ./bash
echo ".bashrc copied successfully in /Bash"
echo ""

cp ~/.config/termite/config ./termite
echo "termite conf copied successfully in /Termite"
echo ""

cp ~/.config/kitty/kitty.conf ./kitty
echo "kitty conf copied successfully in /Kitty"
echo ""

cp ~/.config/alacritty/alacritty.yml ./alacritty
echo "alacritty.yml copied successfully in /alacritty"
echo ""
